[package]
name = "saorsa-gossip"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "CLI tool for Saorsa Gossip network - demo and testing"

[[bin]]
name = "saorsa-gossip"
path = "src/main.rs"

[dependencies]
# CLI
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"
shellexpand = "3.1"

# Async runtime
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Crypto
saorsa-pqc = { workspace = true }

# Workspace crates
saorsa-gossip-types = { version = "0.1.3", path = "../../crates/types" }
saorsa-gossip-identity = { version = "0.1.3", path = "../../crates/identity" }
saorsa-gossip-transport = { version = "0.1.3", path = "../../crates/transport" }
saorsa-gossip-coordinator = { version = "0.1.3", path = "../../crates/coordinator" }
saorsa-gossip-membership = { version = "0.1.3", path = "../../crates/membership" }
saorsa-gossip-pubsub = { version = "0.1.3", path = "../../crates/pubsub" }
saorsa-gossip-rendezvous = { version = "0.1.3", path = "../../crates/rendezvous" }
saorsa-gossip-groups = { version = "0.1.3", path = "../../crates/groups" }
saorsa-gossip-presence = { version = "0.1.3", path = "../../crates/presence" }
saorsa-gossip-crdt-sync = { version = "0.1.3", path = "../../crates/crdt-sync" }
