[package]
name = "saorsa-gossip-transport"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "QUIC transport for Saorsa Gossip with ant-quic, NAT traversal, and stream multiplexing"
keywords = ["p2p", "gossip", "quic", "nat-traversal", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
saorsa-gossip-types = { version = "0.1.3", path = "../types" }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
ant-quic = "0.10.3"
serde = { workspace = true }
bincode = { workspace = true }
dirs = "5.0"
uuid = { version = "1.6", features = ["v4"] }
futures = "0.3"

[dev-dependencies]
proptest = { workspace = true }
tracing-subscriber = "0.3"

[[example]]
name = "throughput_test"
path = "../../examples/throughput_test.rs"

[[example]]
name = "transport_benchmark"
path = "../../examples/transport_benchmark.rs"
